plugins {
    id 'dev.architectury.loom' version '1.6-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    mixin {
        defaultRefmapName = "takeitout.refmap.json"
    }

    forge {
        mixinConfigs = [
                "takeitout.mixins.json"
        ]
    }
}

repositories {
    mavenCentral()
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.fallenbreath.me/releases" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    forge "net.minecraftforge:forge:${project.forge_version}"

    modImplementation "maven.modrinth:forgematica:${project.forgematica_version}"
    modImplementation "maven.modrinth:mafglib:${project.mafglib_version}"
    modImplementation "maven.modrinth:tweakerge:${project.tweakerge_version}"
    modImplementation "maven.modrinth:forgematicaprinter:${project.forgematicaprinter_version}"

    modCompileOnly "maven.modrinth:TyCTlI4b:${project.sophisticatedbackpacks_version}"
    modCompileOnly "maven.modrinth:nmoqTijg:${project.sophisticatedcore_version}"
    modCompileOnly "maven.modrinth:vvuO3ImH:${project.curios_version}"

    modImplementation "me.fallenbreath:conditional-mixin-forge:${project.conditional_mixin_version}"
    include "me.fallenbreath:conditional-mixin-forge:${project.conditional_mixin_version}"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "forge_version", project.forge_version
    filteringCharset "UTF-8"

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "forge_version": project.forge_version
    }
}

def targetJavaVersion = 17
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
    }
}
