plugins {
    id 'dev.architectury.loom-no-remap' version "1.17-SNAPSHOT"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url = "https://maven.neoforged.net/releases" }
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.fallenbreath.me/releases" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    neoForge "net.neoforged:neoforge:${project.neoforge_version}"

    implementation "maven.modrinth:mafglib:${project.mafglib_version}"
    implementation "maven.modrinth:forgematica:${project.forgematica_version}"

    compileOnly "maven.modrinth:TyCTlI4b:${project.sophisticatedbackpacks_version}"
    compileOnly "maven.modrinth:nmoqTijg:${project.sophisticatedcore_version}"
    compileOnly "maven.modrinth:vvuO3ImH:${project.curios_version}"

    compileOnly "me.fallenbreath:conditional-mixin-neoforge:0.6.4"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "neoforge_version", project.neoforge_version
    filteringCharset "UTF-8"

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(
                "version": project.version,
                "minecraft_version": project.minecraft_version,
                "neoforge_version": project.neoforge_version
        )
    }
}

def targetJavaVersion = 25

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release.set(targetJavaVersion)
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }

    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
    }
}
