# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform=neoforge

minecraft_version=1.21.11
mod_version=1.1.26-1.21.11-neoforge
maven_group=net.maxbel
archives_base_name=takeitout

neoforge_version=21.11.42
mafglib_version=0.4.3+mc1.21.11
forgematica_version=0.4.2+mc1.21.11
tweakerge_version=0.4.0+mc1.21.11
